,1,1,1,1,4,8);"]
Traceback (most recent call last):
  File "tweet_processor.py", line 257, in run
  File "tweet_processor.py", line 177, in process_tweets
  File "SimpleClient.py", line 108, in send_batch
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cluster.py", line 1009, in execute
    result = future.result(timeout)
  File "/usr/local/lib/python2.7/dist-packages/cassandra/cluster.py", line 2279, in result
    raise self._final_exception
InvalidRequest: code=2200 [Invalid query] message="unable to coerce '2013 10 13 14 16 48' to a  formatted date (long)"

